### ISSUE TITLE
open new accounts and new branch's with required details and update in the database

### ISSUE THREAD

**Issue by gsaiganesh283** [gsaiganesh283/online-banking-PHP#10]

**Comment by DURGABHAVANI66** [comment]
![image](https://github.com/gsaiganesh283/online-banking-PHP/assets/103325696/79e8bc4b-2991-4e6a-98c5-5f9f6e47e15a)

new branch are opened successfully.

![image](https://github.com/gsaiganesh283/online-banking-PHP/assets/103325696/bb28f81a-7704-4ad9-9000-3ea203f50cdc)

new branch's opened and the database is represented successfully.

![image](https://github.com/gsaiganesh283/online-banking-PHP/assets/103325696/f9f37036-abfc-46aa-8cdb-abdf899c4b56)

new accounts are opened successfully.

![image](https://github.com/gsaiganesh283/online-banking-PHP/assets/103325696/f11672f1-7de8-44b6-8b38-3785e073c273)

new accounts are opened and the database is represented successfully.

**Comment by DURGABHAVANI66** [comment]
New account opening form is not having the all required details to add into the database.

rise a new issue to solve the issue.

![image](https://github.com/gsaiganesh283/online-banking-PHP/assets/103325696/bd7c7ce5-54d6-4d86-b908-786dee1a6379)

#https://github.com/gsaiganesh283/online-banking-PHP/blob/main/staff/pages_open_acc.php

**Comment by DURGABHAVANI66** [comment]
default password is required when opening a new account in admin portal.
