### ISSUE TITLE
eraser the transitions history data from the database and update it

### ISSUE THREAD

**Issue by gsaiganesh283** [gsaiganesh283/online-banking-PHP#3]

**Comment by DURGABHAVANI66** [comment]
Transaction data has been removed successfully from the database.
And updated in the codespace.

![image](https://github.com/gsaiganesh283/online-banking-PHP/assets/103325696/00281790-46c3-4b62-be5a-cacc2d6e7ff8)
No data in transaction table.
![image](https://github.com/gsaiganesh283/online-banking-PHP/assets/103325696/87965492-62f3-4b27-8533-13e54c457499)
no data represented in the interface.
