### ISSUE TITLE
create aa new branch called SRM NAGAR with required details and check for the error`s

### ISSUE THREAD

**Issue by gsaiganesh283** [gsaiganesh283/online-banking-PHP#5]

**Comment by DURGABHAVANI66** [comment]
New branch called SRM NAGAR has been successfully opened with required data.

![image](https://github.com/gsaiganesh283/online-banking-PHP/assets/103325696/ecbdbbd2-9639-4fd6-a804-bf3796fe1a0c)

**Comment by gsaiganesh283** [comment]
send me the proper screenshot

**Comment by DURGABHAVANI66** [comment]
![Uploading image.png…]()

**Comment by DURGABHAVANI66** [comment]
![image](https://github.com/gsaiganesh283/online-banking-PHP/assets/103325696/c3b9d6a8-25d3-40ee-a077-e051d632a15e)

**Comment by gsaiganesh283** [comment]
review completed
