### ISSUE TITLE
clear the pervious accounts of the user and branchs and update in the database

### ISSUE THREAD

**Issue by gsaiganesh283** [gsaiganesh283/online-banking-PHP#9]

**Comment by DURGABHAVANI66** [comment]
![image](https://github.com/gsaiganesh283/online-banking-PHP/assets/103325696/0913326b-37dd-45f8-ae6e-e9512db85474)

user database is cleared successfully.

![image](https://github.com/gsaiganesh283/online-banking-PHP/assets/103325696/ab2f19e7-0a29-47da-a95b-43d3cb337af0)

branch database is cleared successfully.
